#!/bin/bash
#continuous integration script.

cd $(dirname $0)

export BASEDIR=$(cd ../../..; pwd)

export SEDB=no
export CI_DIR=$(pwd)/.ci
export EXAMPLES_DIR=$BASEDIR/examples
export RELEASE_DIR=$BASEDIR/release

test -d $CI_DIR || mkdir -p $CI_DIR

log=$CI_DIR/log-$(date +'%Y%m%d-%H%M%S')
echo $log

{
    failures=0

    for i in 1 2 4 5 6 7; do # test 3 was removed
        echo "======================================================================"
        echo "test $i"
        echo
        ./test $i $CI_CLEAN || failures=$((failures+1))
    done

    echo "======================================================================"
    echo "test lily"
    echo
    ./test lily $CI_CLEAN || failures=$((failures+1))

    echo "======================================================================"
    echo "build"
    echo
    if pkg=$($RELEASE_DIR/build.sh -clean -ci -prefix build); then
        TMPDIR=$(mktemp -d)
        cd $TMPDIR

        tar xfz $pkg
        if [ -d ./build ]; then
            ln -s build/share/mixup/log.rc .
            for example in $EXAMPLES_DIR/*.mix; do
                echo "======================================================================"
                mix=$(basename $example)
                ln -s $example $mix
                if ./build/bin/mixup $mix; then
                    ly=${mix%.mix}.ly
                    if test -e $ly; then
                        if test -e $EXAMPLE_DIR/reference/$ly; then
                            diff -u $EXAMPLE_DIR/reference/$ly $ly || failures=$((failures+1))
                        fi
                    else
                        echo "Missing $ly! Failed execution?"
                        failures=$((failures+1))
                    fi
                else
                    failures=$((failures+1))
                fi
            done
        else
            echo "Missing build directory! Failed packaging?"
            failures=$((failures+1))
        fi

        rm -rf $TMPDIR
    else
        failures=$((failures+1))
    fi

    echo "======================================================================"
    if [ $failures -eq 0 ]; then
        echo "SUCCESS"
    else
        echo "Failures: $failures"
    fi
} >$log 2>&1

tail -n 1 $log | grep SUCCESS || echo 'FAILED!'
